/**
 * Captures the built index.html as a TypeScript module the preview function can
 * import. Run automatically after `vite build`.
 *
 * The function needs the real shell — with the hashed asset filenames from this
 * exact build — so a shared link serves a working app, not just meta tags.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const shell = readFileSync('dist/index.html', 'utf8');

if (!/<div id="root">/.test(shell)) {
  console.error('dist/index.html does not look like the app shell — refusing to write.');
  process.exit(1);
}

mkdirSync('api', { recursive: true });
writeFileSync(
  'api/_shell.ts',
  `/* GENERATED by scripts/build-shell.mjs — do not edit. */\n` +
    `export const APP_SHELL = ${JSON.stringify(shell)};\n`,
);

const assets = [...shell.matchAll(/\/assets\/[A-Za-z0-9._-]+/g)].map((m) => m[0]);
console.log(`  api/_shell.ts written (${(shell.length / 1024).toFixed(1)} KB)`);
console.log(`  assets referenced: ${assets.join(', ') || 'none'}`);
