/**
 * Prepares the link-preview function.
 *
 * Two steps, run after `vite build`:
 *
 * 1. Capture the built index.html as a module, so the function serves the real
 *    app with THIS build's hashed asset names rather than a stale copy.
 *
 * 2. Bundle src/share/preview.ts into a single self-contained api/build-meta.js.
 *
 * Step 2 exists because Vercel does not bundle cross-directory TypeScript
 * imports for functions. An `api/*.ts` file that imports from `../src` compiles
 * fine but crashes at invocation with FUNCTION_INVOCATION_FAILED, because the
 * import is left as a runtime specifier that cannot resolve. Bundling it
 * ourselves removes the whole class of problem — the deployed function has no
 * external imports at all.
 *
 * The bundle is committed so the deployed artifact never depends on build
 * ordering. `npm run build` regenerates it; if it is up to date, git shows no
 * diff.
 */

import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, mkdirSync, statSync } from 'node:fs';

const shell = readFileSync('dist/index.html', 'utf8');

if (!/<div id="root">/.test(shell)) {
  console.error('dist/index.html does not look like the app shell — refusing to write.');
  process.exit(1);
}

writeFileSync(
  'src/share/_shell.ts',
  '/* GENERATED by scripts/build-shell.mjs — do not edit. */\n' +
    `export const APP_SHELL = ${JSON.stringify(shell)};\n`,
);

mkdirSync('api', { recursive: true });

execSync(
  'npx --yes esbuild src/share/preview.ts --bundle --platform=node --format=esm ' +
    '--outfile="api/build-meta.js" --log-level=error',
  { stdio: 'inherit' },
);

const bundled = readFileSync('api/build-meta.js', 'utf8');
if (/from\s+["']\.\.?\//.test(bundled)) {
  console.error('api/build-meta.js still has relative imports — it would crash on Vercel.');
  process.exit(1);
}

const assets = [...shell.matchAll(/\/assets\/[A-Za-z0-9._-]+/g)].map((m) => m[0]);
console.log(`  src/share/_shell.ts   ${(shell.length / 1024).toFixed(1)} KB`);
console.log(`  api/build-meta.js     ${(statSync('api/build-meta.js').size / 1024).toFixed(0)} KB, self-contained`);
console.log(`  assets referenced     ${assets.join(', ') || 'none'}`);
