/**
 * The single place the app gets its game data from.
 *
 * These JSON files are generated by `npm run convert` — never edit them by hand.
 * If something is wrong, fix data/starting-equipment.json or data/patches.json
 * and run the converter again.
 */

import weaponsJson from './weapons.json';
import shieldsJson from './shields.json';
import armorsJson from './armors.json';
import talismansJson from './talismans.json';
import sorceriesJson from './sorceries.json';
import incantationsJson from './incantations.json';
import classesJson from './classes.json';
import ashesJson from './ashes.json';

import type {
  Weapon, Shield, Armor, Talisman, Sorcery, Incantation, StartingClass,
} from '../types/game-data';

export const weapons = weaponsJson as unknown as Record<string, Weapon>;
export const shields = shieldsJson as unknown as Record<string, Shield>;
export const armors = armorsJson as unknown as Record<string, Armor>;
export const talismans = talismansJson as unknown as Record<string, Talisman>;
export const sorceries = sorceriesJson as unknown as Record<string, Sorcery>;
export const incantations = incantationsJson as unknown as Record<string, Incantation>;
export const classes = classesJson as unknown as Record<string, StartingClass>;

/** Handy list versions for rendering. */
export const weaponList = Object.values(weapons);
export const shieldList = Object.values(shields);
export const armorList = Object.values(armors);
export const talismanList = Object.values(talismans);
export const sorceryList = Object.values(sorceries);
export const incantationList = Object.values(incantations);

/** Classes in the order the game shows them. */
const CLASS_ORDER = [
  'vagabond', 'warrior', 'hero', 'bandit', 'astrologer',
  'prophet', 'samurai', 'prisoner', 'confessor', 'wretch',
];

export const classList = CLASS_ORDER.map((id) => classes[id]).filter(Boolean);

/* ------------------------------------------------------------------ */
/* Ashes of War                                                        */
/* ------------------------------------------------------------------ */

export interface AshOfWar {
  id: number;
  /** Skill name, e.g. "Seppuku" — the "Ash of War:" prefix is stripped. */
  name: string;
  itemName: string;
  skillId: number;
  skillName: string | null;
  fpCost: number;
  defaultAffinity: number;
  /** Affinity ids this Ash can apply. */
  affinities: number[];
  /** Weapon class ids it can be applied to. */
  weaponTypes: number[];
}

export const ashes = (ashesJson as { ashes: AshOfWar[] }).ashes;

export const ashList = [...ashes].sort((a, b) => a.name.localeCompare(b.name));

/**
 * Which Ashes can put this affinity on this weapon class. Used to turn
 * "requires Blood infusion" into something you can actually go and do.
 */
export function ashesFor(affinityId: number, weaponType: number): AshOfWar[] {
  return ashes
    .filter((a) => a.affinities.includes(affinityId) && a.weaponTypes.includes(weaponType))
    .sort((a, b) => {
      // Ashes whose default is this affinity are the natural suggestion.
      const ad = a.defaultAffinity === affinityId ? 0 : 1;
      const bd = b.defaultAffinity === affinityId ? 0 : 1;
      return ad - bd || a.name.localeCompare(b.name);
    });
}
